language: generic
git:
  quiet: true
  depth: 10
branches:
  only:
  - master
  - /^deploy-.*$/
sudo: required
services:
  - docker
env:
  - TF_VERSION=0.11.11 IMAGE_NAME=enichols/tf-tester

# before_install: 

jobs:
  include:
    - stage: validate
      # if: type = commit
      install: true
      script:
        - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
        - docker run ${IMAGE_NAME} terraform --validate
    # - stage: full
    #   if: type = push AND branch = master
    #   install: true
    #   script:
    #     - docker build --build-arg BUILD_TERRAFORM_VERSION=${TERRAFORM_VERSION} --build-arg BUILD_ARM_SUBSCRIPTION_ID=$ARM_SUBSCRIPTION_ID --build-arg BUILD_ARM_CLIENT_ID=$ARM_CLIENT_ID --build-arg BUILD_ARM_CLIENT_SECRET=$ARM_CLIENT_SECRET --build-arg BUILD_ARM_TENANT_ID=$ARM_TENANT_ID -t ${IMAGE_NAME} .
    #     - docker run ${IMAGE_NAME} rake full